"""
Problem 1: Multiples of 3 or 5
    
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
    
Find the sum of all the multiples of 3 or 5 below 1000.

"""
function problem_1(max=1000)
    sum = 0
    a = collect(1:max-1)
    for i in a
        if i%3==0 || i%5==0
            sum = sum + i
        end
    end
    return sum
end

function problem_1B(max=1000)
    sum = 0
    i=1
    while i<max
        if i%3==0 || i%5==0
            sum = sum + i
        end
        i = i+1
    end
    return sum
end

function problem_1C(max=1000)
    sum = 0.0
    i=1
    while i<max
        if i%3==0 || i%5==0
            sum = sum + i
        end
        i = i+1
    end
    return sum
end

# Compare with numpy
#def problem_1(max=1000):
#    x=np.array(range(1,max)).astype(np.int64)
#    return np.sum(x[np.logical_or(x%3==0,x%5==0)])

"""
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""
function problem_2()
    max=4e6
    sum=0
    fibon0=0
    fibon1=1
    fibon=fibon0+fibon1
    while fibon<max
        fibon=fibon0+fibon1
        fibon0=fibon1
        fibon1=fibon
        if fibon%2==0
            sum=sum+fibon
        end
    end
    return sum
end

"""
Problem 3: Largest prime factor

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?
"""
function problem_3()
    return -1
end
    
export problem_1
export problem_2
export problem_3
